### ISSUE TITLE
1. При подключении CI Appveyor появляется сообщение BUILD FAILED

### ISSUE THREAD

**Issue by denis290788** [denis290788/aqa-hw-2.3#1]
Локально тест проходит, но при подключении CI в Appveyor появляется сообщение BUILD FAILED. Тексты ошибок "error: package lombok does not exist"
"error: package com.github.javafaker does not exist".
При программировании авто-тестов использовались библиотека Faker и плагин Lombok.
Ниже скрины логов в Appveyor.

![Screenshot](https://user-images.githubusercontent.com/58230686/71556619-0d76ec00-2a4c-11ea-86d0-3ee321ce6462.png)

![Screenshot (1)](https://user-images.githubusercontent.com/58230686/71556621-0fd94600-2a4c-11ea-885e-c3d98894477f.png)

![Screenshot (2)](https://user-images.githubusercontent.com/58230686/71556622-11a30980-2a4c-11ea-910c-07cf664c66ab.png)

[https://github.com/denis290788/aqa-hw-2.3.git](url)

**Comment by ArRomanov** [comment]
Если у вас сейчас актуальный код в репозитории, то в файле build.gradle не хватает зависимостей для соответствующих библиотек (lombok, faker)
